import localFont from "next/font/local";
import dynamic from 'next/dynamic';
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import { ThemeProvider } from "@/app/components/theme-provider";
import { Provider } from "react-redux";
  // Ensure you're importing from the correct path
import { StoreProvider } from "./Redux/StoreProvider";

// Font definitions
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",  // Use the correct path from the public folder
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "/fonts/GeistMonoVF.woff",  // Use the correct path from the public folder
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata = {
  title: "MERN Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
            <NavBar />
            {children}
          </ThemeProvider>
        
      </body>
    </html>
    </StoreProvider>
  );
}
